export const SAVE_RECENT_ITEM_START = 'SAVE_RECENT_ITEM_START'
export const SAVE_RECENT_ITEM_SUCCESS = 'SAVE_RECENT_ITEM_SUCCESS'
export const SAVE_RECENT_ITEM_FAILURE = 'SAVE_RECENT_ITEM_FAILURE'

export const REMOVE_RECENT_ITEM_START = 'REMOVE_RECENT_ITEM_START'
export const REMOVE_RECENT_ITEM_SUCCESS = 'REMOVE_RECENT_ITEM_SUCCESS'
export const REMOVE_RECENT_ITEM_FAILURE = 'REMOVE_RECENT_ITEM_FAILURE'

export const RECENT_ITEMS_FETCH_START = 'RECENT_ITEMS_FETCH_START'
export const RECENT_ITEMS_FETCH_SUCCESS = 'RECENT_ITEMS_FETCH_SUCCESS'
export const RECENT_ITEMS_FETCH_FAILURE = 'RECENT_ITEMS_FETCH_FAILURE'
