export const SEARCH_START = 'SEARCH_START'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAILURE = 'SEARCH_FAILURE'

export const SEARCH_ALL_START = 'SEARCH_ALL_START'
export const SEARCH_ALL_SUCCESS = 'SEARCH_ALL_SUCCESS'
export const SEARCH_ALL_FAILURE = 'SEARCH_ALL_FAILURE'

export const CHANGE_SEARCH_QUERY = 'CHANGE_SEARCH_QUERY'
export const SAVE_SEARCH_QUERY = 'SAVE_SEARCH_QUERY'

export const FLUSH_SEARCH = 'FLUSH_SEARCH'

export const SAVE_SEARCH_QUERY_START = 'SAVE_SEARCH_QUERY_START'
export const SAVE_SEARCH_QUERY_SUCCESS = 'SAVE_SEARCH_QUERY_SUCCESS'
export const SAVE_SEARCH_QUERY_FAILURE = 'SAVE_SEARCH_QUERY_FAILURE'

export const SEARCH_QUERIES_FETCH_START = 'SEARCH_QUERIES_FETCH_START'
export const SEARCH_QUERIES_FETCH_SUCCESS = 'SEARCH_QUERIES_FETCH_SUCCESS'
export const SEARCH_QUERIES_FETCH_FAILURE = 'SEARCH_QUERIES_FETCH_FAILURE'

export const TOGGLE_SEARCH_MODAL = 'TOGGLE_SEARCH_MODAL'
