export const UPDATE_TOKEN = 'UPDATE_TOKEN'

export const LOG_OUT_START = 'LOG_OUT_START'
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE'

export const REMOVE_TOKEN = 'REMOVE_TOKEN'
