export const DEPARTMENT_FETCH_START = 'DEPARTMENT_FETCH_START'
export const DEPARTMENT_FETCH_SUCCESS = 'DEPARTMENT_FETCH_SUCCESS'
export const DEPARTMENT_FETCH_FAILURE = 'DEPARTMENT_FETCH_FAILURE'

export const DEPARTMENT_DOCUMENTS_FETCH_START = 'DEPARTMENT_DOCUMENTS_FETCH_START'
export const DEPARTMENT_DOCUMENTS_FETCH_SUCCESS = 'DEPARTMENT_DOCUMENTS_FETCH_SUCCESS'
export const DEPARTMENT_DOCUMENTS_FETCH_FAILURE = 'DEPARTMENT_DOCUMENTS_FETCH_FAILURE'
