export const DEPARTMENT_FETCH_START = 'DEPARTMENT_FETCH_START'
export const DEPARTMENT_FETCH_SUCCESS = 'DEPARTMENT_FETCH_SUCCESS'
export const DEPARTMENT_FETCH_FAILURE = 'DEPARTMENT_FETCH_FAILURE'

export const DOCUMENTS_FETCH_START = 'DOCUMENTS_FETCH_START'
export const DOCUMENTS_FETCH_SUCCESS = 'DOCUMENTS_FETCH_SUCCESS'
export const DOCUMENTS_FETCH_FAILURE = 'DOCUMENTS_FETCH_FAILURE'
