export const DEPARTMENT_FETCH_START = 'DEPARTMENT_FETCH_START'
export const DEPARTMENT_FETCH_SUCCESS = 'DEPARTMENT_FETCH_SUCCESS'
export const DEPARTMENT_FETCH_FAILURE = 'DEPARTMENT_FETCH_FAILURE'

export const DEPARTMENT_FEATURED_OFFICERS_FETCH_START =
  'DEPARTMENT_FEATURED_OFFICERS_FETCH_START'
export const DEPARTMENT_FEATURED_OFFICERS_FETCH_SUCCESS =
  'DEPARTMENT_FEATURED_OFFICERS_FETCH_SUCCESS'
export const DEPARTMENT_FEATURED_OFFICERS_FETCH_FAILURE =
  'DEPARTMENT_FEATURED_OFFICERS_FETCH_FAILURE'

export const DEPARTMENT_FEATURED_DOCUMENTS_FETCH_START =
  'DEPARTMENT_FEATURED_DOCUMENTS_FETCH_START'
export const DEPARTMENT_FEATURED_DOCUMENTS_FETCH_SUCCESS =
  'DEPARTMENT_FEATURED_DOCUMENTS_FETCH_SUCCESS'
export const DEPARTMENT_FEATURED_DOCUMENTS_FETCH_FAILURE =
  'DEPARTMENT_FEATURED_DOCUMENTS_FETCH_FAILURE'

export const DEPARTMENT_FEATURED_NEWS_ARTICLES_FETCH_START =
  'DEPARTMENT_FEATURED_NEWS_ARTICLES_FETCH_START'
export const DEPARTMENT_FEATURED_NEWS_ARTICLES_FETCH_SUCCESS =
  'DEPARTMENT_FEATURED_NEWS_ARTICLES_FETCH_SUCCESS'
export const DEPARTMENT_FEATURED_NEWS_ARTICLES_FETCH_FAILURE =
  'DEPARTMENT_FEATURED_NEWS_ARTICLES_FETCH_FAILURE'

export const DEPARTMENT_DATASETS_FETCH_START = 'DEPARTMENT_DATASETS_FETCH_START'
export const DEPARTMENT_DATASETS_FETCH_SUCCESS =
  'DEPARTMENT_DATASETS_FETCH_SUCCESS'
export const DEPARTMENT_DATASETS_FETCH_FAILURE =
  'DEPARTMENT_DATASETS_FETCH_FAILURE'

export const SEARCH_ITEMS_START = 'SEARCH_ITEMS_START'
export const SEARCH_ITEMS_SUCCESS = 'SEARCH_ITEMS_SUCCESS'
export const SEARCH_ITEMS_FAILURE = 'SEARCH_ITEMS_FAILURE'

export const CLEAR_DEPARTMENT_SEARCH_RESULTS = 'CLEAR_DEPARTMENT_SEARCH_RESULTS'
