export const ANALYTIC_SUMMARY_FETCH_START = 'ANALYTIC_SUMMARY_FETCH_START'
export const ANALYTIC_SUMMARY_FETCH_SUCCESS = 'ANALYTIC_SUMMARY_FETCH_SUCCESS'
export const ANALYTIC_SUMMARY_FETCH_FAILURE = 'ANALYTIC_SUMMARY_FETCH_FAILURE'

export const RECENT_ITEMS_FETCH_START = 'RECENT_ITEMS_FETCH_START'
export const RECENT_ITEMS_FETCH_SUCCESS = 'RECENT_ITEMS_FETCH_SUCCESS'
export const RECENT_ITEMS_FETCH_FAILURE = 'RECENT_ITEMS_FETCH_FAILURE'

export const DEPARTMENTS_FETCH_START = 'DEPARTMENTS_FETCH_START'
export const DEPARTMENTS_FETCH_SUCCESS = 'DEPARTMENTS_FETCH_SUCCESS'
export const DEPARTMENTS_FETCH_FAILURE = 'DEPARTMENTS_FETCH_FAILURE'

export const OFFICERS_FETCH_START = 'OFFICERS_FETCH_START'
export const OFFICERS_FETCH_SUCCESS = 'OFFICERS_FETCH_SUCCESS'
export const OFFICERS_FETCH_FAILURE = 'OFFICERS_FETCH_FAILURE'

export const DOCUMENTS_FETCH_START = 'DOCUMENTS_FETCH_START'
export const DOCUMENTS_FETCH_SUCCESS = 'DOCUMENTS_FETCH_SUCCESS'
export const DOCUMENTS_FETCH_FAILURE = 'DOCUMENTS_FETCH_FAILURE'
