export const ANALYTIC_SUMMARY_FETCH_START = 'ANALYTIC_SUMMARY_FETCH_START'
export const ANALYTIC_SUMMARY_FETCH_SUCCESS = 'ANALYTIC_SUMMARY_FETCH_SUCCESS'
export const ANALYTIC_SUMMARY_FETCH_FAILURE = 'ANALYTIC_SUMMARY_FETCH_FAILURE'

export const DEPARTMENTS_FETCH_START = 'DEPARTMENTS_FETCH_START'
export const DEPARTMENTS_FETCH_SUCCESS = 'DEPARTMENTS_FETCH_SUCCESS'
export const DEPARTMENTS_FETCH_FAILURE = 'DEPARTMENTS_FETCH_FAILURE'

export const OFFICERS_FETCH_START = 'OFFICERS_FETCH_START'
export const OFFICERS_FETCH_SUCCESS = 'OFFICERS_FETCH_SUCCESS'
export const OFFICERS_FETCH_FAILURE = 'OFFICERS_FETCH_FAILURE'

export const DOCUMENTS_FETCH_START = 'DOCUMENTS_FETCH_START'
export const DOCUMENTS_FETCH_SUCCESS = 'DOCUMENTS_FETCH_SUCCESS'
export const DOCUMENTS_FETCH_FAILURE = 'DOCUMENTS_FETCH_FAILURE'

export const NEWS_ARTICLES_FETCH_START = 'NEWS_ARTICLES_FETCH_START'
export const NEWS_ARTICLES_FETCH_SUCCESS = 'NEWS_ARTICLES_FETCH_SUCCESS'
export const NEWS_ARTICLES_FETCH_FAILURE = 'NEWS_ARTICLES_FETCH_FAILURE'

export const FRONT_PAGE_ORDERS_FETCH_START = 'FRONT_PAGE_ORDERS_FETCH_START'
export const FRONT_PAGE_ORDERS_FETCH_SUCCESS = 'FRONT_PAGE_ORDERS_FETCH_SUCCESS'
export const FRONT_PAGE_ORDERS_FETCH_FAILURE = 'FRONT_PAGE_ORDERS_FETCH_FAILURE'

export const FRONT_PAGE_CARDS_FETCH_START = 'FRONT_PAGE_CARDS_FETCH_START'
export const FRONT_PAGE_CARDS_FETCH_SUCCESS = 'FRONT_PAGE_CARDS_FETCH_SUCCESS'
export const FRONT_PAGE_CARDS_FETCH_FAILURE = 'FRONT_PAGE_CARDS_FETCH_FAILURE'

export const MIGRATORY_DATA_FETCH_START = 'MIGRATORY_DATA_FETCH_START'
export const MIGRATORY_DATA_FETCH_SUCCESS = 'MIGRATORY_DATA_FETCH_SUCCESS'
export const MIGRATORY_DATA_FETCH_FAILURE = 'MIGRATORY_DATA_FETCH_FAILURE'

export const NEWS_ARTICLE_HIDE_START = 'NEWS_ARTICLE_HIDE_START'
export const NEWS_ARTICLE_HIDE_SUCCESS = 'NEWS_ARTICLE_HIDE_SUCCESS'
export const NEWS_ARTICLE_HIDE_FAILURE = 'NEWS_ARTICLE_HIDE_FAILURE'

export const SET_MAP_CURRENT_INDEX = 'SET_MAP_CURRENT_INDEX'
