export const OFFICER_FETCH_START = 'OFFICER_FETCH_START'
export const OFFICER_FETCH_SUCCESS = 'OFFICER_FETCH_SUCCESS'
export const OFFICER_FETCH_FAILURE = 'OFFICER_FETCH_FAILURE'

export const OFFICER_TIMELINE_FETCH_START = 'OFFICER_TIMELINE_FETCH_START'
export const OFFICER_TIMELINE_FETCH_SUCCESS = 'OFFICER_TIMELINE_FETCH_SUCCESS'
export const OFFICER_TIMELINE_FETCH_FAILURE = 'OFFICER_TIMELINE_FETCH_FAILURE'

export const OFFICER_TIMELINE_DOWNLOAD_START = 'OFFICER_TIMELINE_DOWNLOAD_START'
export const OFFICER_TIMELINE_DOWNLOAD_SUCCESS =
  'OFFICER_TIMELINE_DOWNLOAD_SUCCESS'
export const OFFICER_TIMELINE_DOWNLOAD_FAILURE =
  'OFFICER_TIMELINE_DOWNLOAD_FAILURE'

export const CHANGE_FILTER_GROUP_KEY = 'CHANGE_FILTER_GROUP_KEY'
