export const OFFICER_FETCH_START = 'OFFICER_FETCH_START'
export const OFFICER_FETCH_SUCCESS = 'OFFICER_FETCH_SUCCESS'
export const OFFICER_FETCH_FAILURE = 'OFFICER_FETCH_FAILURE'

export const OFFICER_DOCUMENTS_FETCH_START =
  'OFFICER_DOCUMENTS_FETCH_START'
export const OFFICER_DOCUMENTS_FETCH_SUCCESS =
  'OFFICER_DOCUMENTS_FETCH_SUCCESS'
export const OFFICER_DOCUMENTS_FETCH_FAILURE =
  'OFFICER_DOCUMENTS_FETCH_FAILURE'

export const OFFICER_TIMELINE_FETCH_START =
  'OFFICER_TIMELINE_FETCH_START'
export const OFFICER_TIMELINE_FETCH_SUCCESS =
  'OFFICER_TIMELINE_FETCH_SUCCESS'
export const OFFICER_TIMELINE_FETCH_FAILURE =
  'OFFICER_TIMELINE_FETCH_FAILURE'
