export const SEARCH_START = 'SEARCH_START'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAILURE = 'SEARCH_FAILURE'

export const CHANGE_SEARCH_QUERY = 'CHANGE_SEARCH_QUERY'
export const SAVE_SEARCH_QUERY = 'SAVE_SEARCH_QUERY'

export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS'

export const SAVE_SEARCH_QUERY_START = 'SAVE_SEARCH_QUERY_START'
export const SAVE_SEARCH_QUERY_SUCCESS = 'SAVE_SEARCH_QUERY_SUCCESS'
export const SAVE_SEARCH_QUERY_FAILURE = 'SAVE_SEARCH_QUERY_FAILURE'

export const SEARCH_QUERIES_FETCH_START = 'SEARCH_QUERIES_FETCH_START'
export const SEARCH_QUERIES_FETCH_SUCCESS = 'SEARCH_QUERIES_FETCH_SUCCESS'
export const SEARCH_QUERIES_FETCH_FAILURE = 'SEARCH_QUERIES_FETCH_FAILURE'

export const CHANGE_SEARCH_DEPARTMENT = 'CHANGE_SEARCH_DEPARTMENT'
