export const SEARCH_START = 'SEARCH_START'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAILURE = 'SEARCH_FAILURE'

export const CHANGE_SEARCH_QUERY = 'CHANGE_SEARCH_QUERY'
export const SAVE_SEARCH_QUERY = 'SAVE_SEARCH_QUERY'
